kafka.collector.bootstrap-servers=localhost:9092
kafka.collector.sensor-topic=telemetry.sensors.v1
kafka.collector.hub-topic=telemetry.hubs.v1
kafka.collector.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.collector.value-serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer