kafka:
  aggregator:
    bootstrap-servers: localhost:9092
    sensor-topic: telemetry.sensors.v1
    snapshot-topic: telemetry.snapshots.v1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.yandex.practicum.kafka.serializer.SensorEventDeserializer
      group-id: aggregator-group
      client-id: consumer-1
      properties:
        fetch.min.bytes: 1
        max.poll.records: 100
        enable.auto.commit: false
        fetch.max.wait.ms: 1000
        max.partition.fetch.bytes: 1048576

logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      springframework: Error
      hibernate.SQL: DEBUG
      orm.jdbc.bind: TRACE
      apache.kafka: WARN