kafka.analyzer.bootstrap-servers=localhost:9092

kafka.analyzer.consumers.consumer-hub.topic=telemetry.hubs.v1
kafka.analyzer.consumers.consumer-hub.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.analyzer.consumers.consumer-hub.value-deserializer=ru.yandex.practicum.kafka.serializer.HubEventDeserializer
kafka.analyzer.consumers.consumer-hub.group-id=analyzer-hub-group
kafka.analyzer.consumers.consumer-hub.client-id=consumer-hub-1
kafka.analyzer.consumers.consumer-hub.properties.fetch.min.bytes=1
kafka.analyzer.consumers.consumer-hub.properties.max.poll.records=100
kafka.analyzer.consumers.consumer-hub.properties.enable.auto.commit=true
kafka.analyzer.consumers.consumer-hub.properties.fetch.max.wait.ms=1000
kafka.analyzer.consumers.consumer-hub.properties.max.partition.fetch.bytes=1048576

kafka.analyzer.consumers.consumer-snapshot.topic=telemetry.snapshots.v1
kafka.analyzer.consumers.consumer-snapshot.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.analyzer.consumers.consumer-snapshot.value-deserializer=ru.yandex.practicum.kafka.serializer.SensorSnapshotDeserializer
kafka.analyzer.consumers.consumer-snapshot.group-id=analyzer-snapshot-group
kafka.analyzer.consumers.consumer-snapshot.client-id=consumer-snapshot-1
kafka.analyzer.consumers.consumer-snapshot.properties.fetch.min.bytes=1
kafka.analyzer.consumers.consumer-snapshot.properties.max.poll.records=100
kafka.analyzer.consumers.consumer-snapshot.properties.enable.auto.commit=false
kafka.analyzer.consumers.consumer-snapshot.properties.fetch.max.wait.ms=1000
kafka.analyzer.consumers.consumer-snapshot.properties.max.partition.fetch.bytes=1048576

grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext

# --- DataSource (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/telemetry_analyzer
spring.datasource.username=dbuser
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true